services:
  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  elastic-search:
    image: elasticsearch:9.3.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
      - ELASTIC_USERNAME=user
    ports:
      - "9200:9200"
      - "9300:9300"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "password"]
